use earthquakesbasic;

drop table earthquakes;
drop table earthquakes_closest_city;
drop table earthquakes_closest_city_discance_to_all_stations;
drop table earthquakes_closest_city_station;
drop table earthquakes_distance_to_all_cities;
drop table earthquakes_distance_to_cities;
drop table earthquakes_full_dataset;